name: "Release on tag"
on:
  push:
    tags:
      - "v*"
env:
    CI: false
jobs:
  tagged-release:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}